1558731158109	Sync.LogManager	DEBUG	Flushing file log
1558731158154	Sync.LogManager	DEBUG	Log cleanup threshold time: 1557867158154
1558731158239	Sync.LogManager	DEBUG	Done deleting files.
1558731159038	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558731160084	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558731166103	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558731167850	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558731167850	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558731167853	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558731168849	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558731177977	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558731177978	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558731177986	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558731177987	Sync.Service	INFO	Starting sync at 2019-05-24 14:52:57 in browser session Ld_FmWfv3Jv4
1558731177987	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558731177991	Sync.Status	INFO	Resetting Status.
1558731177991	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1558731178976	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558731222881	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558731288052	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558731294158	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558731358156	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1558731358157	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558731358157	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558731358157	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1558731358160	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558731358167	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
