1558666952371	Sync.LogManager	DEBUG	Flushing file log
1558666952402	Sync.LogManager	DEBUG	Log cleanup threshold time: 1557802952402
1558666952444	Sync.LogManager	DEBUG	Done deleting files.
1558666952936	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558666952936	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558666952942	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558666952942	Sync.Service	INFO	Starting sync at 2019-05-23 21:02:32 in browser session EmC99OI5yL9m
1558666952943	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558666952948	Sync.Status	INFO	Resetting Status.
1558666952948	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1558666953075	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558666953075	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558666953075	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558666953076	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558666953077	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558666953082	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
