1558669649050	Sync.LogManager	DEBUG	Flushing file log
1558669649052	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://profile.accounts.firefox.com/v1/profile
1558669649052	Services.Common.RESTRequest	TRACE	Channel for GET https://profile.accounts.firefox.com/v1/profile returned status code 2152398878
1558669649052	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1558669649052	Services.Common.RESTRequest	TRACE	GET body: 
1558669649053	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]"}
1558669649062	Sync.LogManager	DEBUG	Log cleanup threshold time: 1557805649062
1558669649109	Sync.LogManager	DEBUG	Done deleting files.
1558669649966	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558669651133	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558669651133	Sync.Service	INFO	Starting sync at 2019-05-23 21:47:31 in browser session EmC99OI5yL9m
1558669651134	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558669651138	Sync.Status	INFO	Resetting Status.
1558669651138	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1558669651140	Sync.BrowserIDManager	INFO	Getting keys
1558669651140	Sync.BrowserIDManager	INFO	Getting an assertion from: https://token.services.mozilla.com/1.0/sync/1.5
1558669651141	FirefoxAccounts	DEBUG	enter getAssertion()
1558669651141	FirefoxAccounts	DEBUG	getKeypairAndCertificate: already have keyPair and certificate
1558669651142	FirefoxAccounts	DEBUG	getAssertionFromCert
1558669651143	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1558669651144	Sync.BrowserIDManager	DEBUG	Getting a token
1558669651144	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://token.services.mozilla.com/1.0/sync/1.5
1558669651145	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1558669651145	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1558669651145	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1558669651145	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: ***** (suppressed)
1558669651154	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://token.services.mozilla.com/1.0/sync/1.5
1558669651154	Services.Common.RESTRequest	TRACE	Channel for GET https://token.services.mozilla.com/1.0/sync/1.5 returned status code 2152398878
1558669651155	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1558669651155	Services.Common.RESTRequest	TRACE	GET body: 
1558669651155	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:35:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:58:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:244:13
1558669651155	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1558669651155	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1558669651156	Sync.BrowserIDManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:35:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:58:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:244:13
1558669651159	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1558669651167	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558669651167	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558669651167	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1558669651168	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558669651169	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558669651173	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
