1558586220080	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558586301258	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1558586301259	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558586301262	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1558586302257	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1558586400068	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1558586400068	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1558586400078	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Linux x86_64) FxSync/1.69.0.20190521202118.desktop
1558586400078	Sync.Service	INFO	Starting sync at 2019-05-22 22:40:00 in browser session N4EmVYZJM46x
1558586400078	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1558586400086	Sync.Status	INFO	Resetting Status.
1558586400087	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1558586400102	Sync.Resource	WARN	GET request to https://sync-548-us-west-2.sync.services.mozilla.com/1.5/84144729/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558586400103	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1558586400103	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1558586400104	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1558586400105	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1558586400112	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
